src/Anuncios/AnuncioBundle/Entity/User.php
<?php

namespace Anuncios\AnuncioBundle\Entity;

use DateTime;
use FOS\UserBundle\Entity\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * User
 */
class User extends BaseUser
{
    protected $id;
    private $userId;
    private $name;
    private $surname;
    private $isJurado;
    private $voting;
    private $createdAt;
    private $updatedAt;


    public function __construct()
    {
        $this->voting = new \Doctrine\Common\Collections\ArrayCollection();
        
        $this->createdAt = new DateTime('now');
        $this->isJurado = false;
        
        parent::__construct();
    }
    
    public function getId()
    {
        return $this->id;
    }

    public function setIsJurado($isJurado)
    {
        $this->isJurado = $isJurado;
    
        return $this;
    }

    public function getIsJurado()
    {
        return $this->isJurado;
    }
    
    public function addVoting(\Anuncios\AnuncioBundle\Entity\Voting $voting)
    {
        $this->voting[] = $voting;
    
        return $this;
    }

    public function removeVoting(\Anuncios\AnuncioBundle\Entity\Voting $voting)
    {
        $this->voting->removeElement($voting);
    }

    public function getVoting()
    {
        return $this->voting;
    }

    public function setUserId($userId)
    {
        $this->userId = $userId;
    
        return $this;
    }
    
    public function getUserId()
    {
        return $this->userId;
    }

    public function setName($name)
    {
        $this->name = $name;
    
        return $this;
    }

    public function getName()
    {
        return $this->name;
    }
    
    public function setSurname($surname)
    {
        $this->surname = $surname;
    
        return $this;
    }

    public function getSurname()
    {
        return $this->surname;
    }
    
    public function getFullname()
    {
    	return $this->getName().' '.$this->getSurname();	
    }
    
    public function isAnuncioVoted($anuncioId)
    {
    	foreach($this->getVoting() as $voting)
    	{
    		if($voting->getAnuncio()->getId() == $anuncioId)
    			return true;
    	}
    	
    	return false;
    }
    
    public function setCreatedAt($createdAt)
    {
    	$this->createdAt = $createdAt;
    
    	return $this;
    }
    
    public function getCreatedAt()
    {
    	return $this->createdAt;
    }
    
    public function setUpdatedAt($updatedAt)
    {
    	$this->updatedAt = $updatedAt;
    
    	return $this;
    }
    
    public function getUpdatedAt()
    {
    	return $this->updatedAt;
    }
}

src/Anuncios/AnuncioBundle/Form/Type/UserType.php
<?php

namespace Anuncios\AnuncioBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('username', 'text', array(
        		'required' => true,
        		'label'    => 'Nombre Usuario'
        ))
        ->add('email', 'text', array(
        		'required' => true,
        		'label'    => 'Email'
        ))
        ->add('name', 'text', array(
        		'required' => true,
        		'label'    => 'Nombre'
        ))
        ->add('surname', 'text', array(
        		'required' => false,
        		'label'    => 'Apellido'
        ))
        ->add('isjurado', 'checkbox', array(
        		'required' => true,
        		'label'    => 'Es Jurado?'
        ));
    }

    public function getName()
    {
        return 'anuncios_user';
    }
}

src/Anuncios/AnuncioBundle/Controller/Backend/CampaignController.php
<?php

namespace Anuncios\AnuncioBundle\Controller\Backend;

use Sylius\Bundle\ResourceBundle\Controller\ResourceController;
use Anuncios\AnuncioBundle\Entity\Category;
use Anuncios\AnuncioBundle\Entity\Anuncio;
use Anuncios\AnuncioBundle\Entity\Resource;
use Anuncios\AnuncioBundle\Entity\Voting;
use Anuncios\AnuncioBundle\Form\Type\ImportCampaignType;
use Symfony\Component\HttpFoundation\Request;
use Anuncios\AnuncioBundle\Entity\Campaign;

class CampaignController extends ResourceController
{
	public function create($resource)
	{
		parent::create($resource);
		
		$form = $this->getForm($resource);
		
		$request = $this->getRequest();
		
		$manager = $this->getDoctrine()->getManager();
		
		if ($request->isMethod('POST') && $form->bind($request)->isValid())
		{
			//Campaña mensual
			if($form->get('month')->getData() != null && $form->get('year')->getData() != null)
			{
				$this->getXmlDocPremios($form->get('month')->getData(), $form->get('year')->getData(), $form->getData());
			}
			
			//Campaña anual
			if($form->get('month')->getData() == null && $form->get('year')->getData() != null)
			{
				$anunciosFinalistas = $this->getAnunciosFinal($form->get('year')->getData());
				
				foreach($anunciosFinalistas as $anuncioFinalista)
				{
					if($anuncioFinalista != null)
					{
						$anuncioFinalista->setCampaign($form->getData());
						$manager->persist($anuncioFinalista);
					}
				}
				
			}
			
			$manager->flush();
		}
		
		$event = $this->dispatchEvent('pre_create', $resource);

        if (!$event->isStopped()) {
            $manager->persist($resource);
            $this->dispatchEvent('create', $resource);
            $manager->flush();
            $this->dispatchEvent('post_create', $resource);
        }

        return $event;
	}
	
	public function importAction(Request $request)
	{	
		$config = $this->getConfiguration();
		$form = $this->createForm(new ImportCampaignType(), null);
	
		$manager = $this->getDoctrine()->getManager();
	
		if ($request->isMethod('POST') && $form->bind($request)->isValid())
		{
			//Campaña mensual
			if($form->get('month')->getData() != null && $form->get('year')->getData() != null && $form->get('category')->getData() != null)
			{
				$this->getXmlDocPremios($form->get('month')->getData(), $form->get('year')->getData(), $form->get('campaign')->getData(), $form->get('category')->getData());
				
				$manager->flush();
				
				$this->get('session')->getFlashBag()->add('success', "Se han importado los anuncios correctamente.");
				
				return $this->redirectToIndex();
			}
		}
	
		$view = $this
            ->view()
            ->setTemplate($config->getTemplate('import.html'))
            ->setData(array(
                'form'                     => $form->createView()
            ))
        ;

        return $this->handleView($view);
	}
	
	public function refreshAnuncioAction(Request $request)
	{
		$manager = $this->getDoctrine()->getManager();
		
		$id = $request->get('id');
		$anuncio = $this->getDoctrine()
			->getRepository('AnunciosAnuncioBundle:Anuncio')
			->find($id);
		
		$month = $anuncio->getCampaign()->getMonth();
		$year = $anuncio->getCampaign()->getYear();
		
		if($month && $year)
		{
			$this->getXmlDocPremios($month, $year, $anuncio->getCampaign(), null, $anuncio);
			$manager->flush();
			$this->get('session')->getFlashBag()->add('success', "Se ha actualizado el anuncio '".$anuncio->getName()."' correctamente.");
		}else
		{
			$this->get('session')->getFlashBag()->add('warning', "No se pudo actualizar el anuncio.");			
		}
		
		return $this->redirect($this->generateUrl('anuncios_anuncio_backend_anuncio_index'));
	}
	
	public function update($resource)
	{
		parent::update($resource);
	
		$form = $this->getForm($resource);
	
		$request = $this->getRequest();
	
		$manager = $this->getDoctrine()->getManager();
	
		if (($request->isMethod('PUT') || $request->isMethod('POST')) && $form->bind($request)->isValid())
		{	
			/*if($form->get('month')->getData() == null && $form->get('year')->getData() != null)
			{
				$anunciosFinalistas = $this->getAnunciosFinal($form->get('year')->getData());
			
				foreach($anunciosFinalistas as $anuncioFinalista)
				{
					if($anuncioFinalista != null)
					{
						$anuncio = clone $anuncioFinalista;
						$anuncio->setCampaign($form->getData());
						$manager->persist($anuncio);
					}
				}
			
				$manager->flush();
			}*/
		}
		
		$event = $this->dispatchEvent('pre_create', $resource);
	
		if (!$event->isStopped()) 
		{
			$manager->persist($resource);
			$this->dispatchEvent('create', $resource);
			$manager->flush();
			$this->dispatchEvent('post_create', $resource);
		}
	
		return $event;
	}
	
	public function finalistasAction($id)
	{
		$campaign = $this->getDoctrine()
			->getRepository('AnunciosAnuncioBundle:Campaign')
			->find($id);
		
		if($campaign->isAnual())
		{
			$categories = $this->getDoctrine()
			->getRepository('AnunciosAnuncioBundle:Category')
			->findAll();
		}else
		{
			$categories = $this->getDoctrine()
			->getRepository('AnunciosAnuncioBundle:Category')
			->getCategoriesWithoutAnual();
		}
		
		$finalistasUsuario = array();
		$finalistasJurado = array();
		
		foreach($categories as $category)
		{
			$finalistasJurado[] = $this->getDoctrine()
				->getRepository('AnunciosAnuncioBundle:Anuncio')
				->getAnunciosVoteByJurado($campaign, $category);
				
			$finalistasUsuario[] = $this->getDoctrine()
				->getRepository('AnunciosAnuncioBundle:Anuncio')
				->getAnunciosVoteByUsuario($campaign, $category);
		}
		
		return $this->render('AnunciosAnuncioBundle:Backend/Campaign:finalistas.html.twig', array(
				'campaign'   => $campaign,
				'finalistasUsuario' => $finalistasUsuario,
				'finalistasJurado'  => $finalistasJurado
		));	
	}
	
	public function rankingAction($id, $type)
	{
		$campaign = $this->getDoctrine()
		->getRepository('AnunciosAnuncioBundle:Campaign')
		->find($id);
	
		if($campaign->isAnual())
		{
			$categories = $this->getDoctrine()
				->getRepository('AnunciosAnuncioBundle:Category')
				->findAll();			
		}else
		{
			$categories = $this->getDoctrine()
				->getRepository('AnunciosAnuncioBundle:Category')
				->getCategoriesWithoutAnual();
		}
	
		$otherType = $type=='usuarios'?'jurados':'usuarios';
		
		//Ranking
		$ranking = array();
		foreach($categories as $category)
		{
			if($type == 'usuarios')
			{
				$catRanking = array(
					'category' => $category,
					'anuncios' =>  $this->getDoctrine()
						->getRepository('AnunciosAnuncioBundle:Anuncio')
						->getAllAnunciosVoteByUsuario($campaign, $category, $campaign->isAnual())
				);
			}else 
			{
				$catRanking = array(
						'category' => $category,
						'anuncios' =>  $this->getDoctrine()
						->getRepository('AnunciosAnuncioBundle:Anuncio')
						->getAllAnunciosVoteByJurado($campaign, $category, $campaign->isAnual())
				);
			}
			$ranking[] = $catRanking;
		}
		
		//Hay Empates?
		$drawCategories = false;
		foreach($categories as $category)
		{
			$anunciosUsuarios = $this->getDoctrine()
				->getRepository('AnunciosAnuncioBundle:Anuncio')
				->getAllAnunciosVoteByUsuario($campaign, $category);
			$anunciosJurados = $this->getDoctrine()
				->getRepository('AnunciosAnuncioBundle:Anuncio')
				->getAllAnunciosVoteByJurado($campaign, $category);
			
			$maxVote = 0;
			if(count($anunciosUsuarios) > 1)
			{
				foreach ($anunciosUsuarios as $anuncio)
				{
					if($anuncio->getVotoUsuario() > $maxVote)
					{
						$maxVote = $anuncio->getVotoUsuario();
					}else if($anuncio->getVotoUsuario() == $maxVote)
					{
						$drawCategories = true;
						break;
					}else if ($anuncio->getVotoUsuario() < $maxVote)
					{
						break;
					}
				}
			}
			
			$maxVote = 0;
			if(count($anunciosJurados) > 1)
			{
				foreach ($anunciosJurados as $anuncio)
				{
					if($anuncio->getVotoJurado() > $maxVote)
					{
						$maxVote = $anuncio->getVotoJurado();
					}else if($anuncio->getVotoJurado() == $maxVote)
					{
						$drawCategories = true;
						break;
					}else if ($anuncio->getVotoJurado() < $maxVote)
					{
						break;
					}
				}
			}
		}
	
		return $this->render('AnunciosAnuncioBundle:Backend/Campaign:ranking.html.twig', array(
				'campaign'   => $campaign,
				'ranking' => $ranking,
				'drawCategories' => $drawCategories,
				'type'  => $type,
				'otherType' => $otherType
		));
	}
	
	public function desdrawingAction($id)
	{
		$campaign = $this->getDoctrine()
			->getRepository('AnunciosAnuncioBundle:Campaign')
			->find($id);
		
		if($campaign->isAnual())
		{
			$categoriesToCheckDraw = $this->getDoctrine()
				->getRepository('AnunciosAnuncioBundle:Category')
				->findAll();
		}else
		{
			$categoriesToCheckDraw = $this->getDoctrine()
				->getRepository('AnunciosAnuncioBundle:Category')
				->getCategoriesWithoutAnual();
		}
		
		foreach($categoriesToCheckDraw as $category)
		{
			$anunciosUsuarios = $this->getDoctrine()
				->getRepository('AnunciosAnuncioBundle:Anuncio')
				->getAllAnunciosVoteByUsuario($campaign, $category, $campaign->isAnual());
			$anunciosJurados = $this->getDoctrine()
				->getRepository('AnunciosAnuncioBundle:Anuncio')
				->getAllAnunciosVoteByJurado($campaign, $category, $campaign->isAnual());
				
			
			//Chequear en usuarios
			$maxVote = 0;
			$anunciosDrawedOnCategory = array();
			foreach ($anunciosUsuarios as $anuncio)
			{
				if($anuncio->getVotoUsuario() > $maxVote)
				{
					$maxVote = $anuncio->getVotoUsuario();
					$anunciosDrawedOnCategory[] = $anuncio;
				}else if($anuncio->getVotoUsuario() == $maxVote)
				{
					$anunciosDrawedOnCategory[] = $anuncio;
				}else if ($anuncio->getVotoUsuario() < $maxVote)
				{
					break;
				}
			}
			
			$this->desdrawAnuncios($anunciosDrawedOnCategory, 'usuarios');
				
			//Chequear en jurados
			$maxVote = 0;
			$anunciosDrawedOnCategory = array();
			foreach ($anunciosJurados as $anuncio)
			{
				if($anuncio->getVotoJurado() > $maxVote)
				{
					$maxVote = $anuncio->getVotoJurado();

src/Anuncios/AnuncioBundle/Controller/Backend/ConfigurationController.php
<?php

namespace Anuncios\AnuncioBundle\Controller\Backend;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Anuncios\AnuncioBundle\Entity\Configuration;
use Sylius\Bundle\ResourceBundle\Controller\ResourceController;
use Symfony\Component\HttpFoundation\Request;

/**
 * Backend configuration controller.
 *
 */
class ConfigurationController extends ResourceController
{
    public function indexAction(Request $request)
    {   	
    	$configuration = $this->getConfigurationObject();    	
    	$configurationForm = $this->getForm($configuration);
    	
        return $this->render('AnunciosAnuncioBundle:Backend/Configuration:index.html.twig', array(
        	'form' => $configurationForm->createView(),
        ));
    }
    
    public function updateAction(Request $request)
    {
    	$configuration = $this->getConfigurationObject();    	
    	$configurationForm = $this->getForm($configuration);
    
    	if ($request->isMethod('POST') && $configurationForm->bind($request)->isValid()) 
    	{
    		$configuration->setUpdatedAt(new \DateTime('now'));
    		
    		//Configuration itself
    		if($configuration->getId())
    		{
	    		$event = $this->update($configuration);
    		}else
    		{
	    		$event = $this->create($configuration);
    		}
    		
    		$values = $request->get('anuncios_configuration');
    		
    		//Password
    		if($values && isset($values['newPassword']) && trim($values['newPassword'] != ''))
    		{
    			$password = $values['newPassword'];
    			$user = $this->get('security.context')->getToken()->getUser();
    			if($user)
    			{
    				$user->setPlainPassword($password);
	    			$this->get('fos_user.user_manager')->updateUser($user);
    			}
    			
    		}
    		
            if (!$event->isStopped()) {
                $this->setFlash('success', 'update');
            }
    	}
        
    	return $this->redirectTo($configuration);
    }
    
    protected function getConfigurationObject()
    {
    	$configuration = $this->getDoctrine()
    		->getRepository('AnunciosAnuncioBundle:Configuration')
    		->findOneBy(array());
    	
    	if(!$configuration)
    	{
    		$configuration = $this->createNew();
    	}
    	
    	return $configuration;
    }
}

src/Anuncios/AnuncioBundle/Resources/views/Backend/User/_form.html.twig
{{ form_errors(form) }}
<div class="row">
    <div class="col-md-6">
		{{ form_row(form.name) }}
		{{ form_row(form.surname) }}
    </div>
    <div class="col-md-6">
    	{{ form_row(form.username) }}
		{{ form_row(form.email) }}
		{{ form_row(form.isjurado) }}
    </div>
</div>
{{ form_rest(form) }}

src/Anuncios/AnuncioBundle/Resources/views/Backend/User/create.html.twig
{% extends 'GeckoBackendBundle::layout.html.twig' %}

{% from 'SyliusResourceBundle:Macros:actions.html.twig' import create %}

{% block topbar %}
<ol class="breadcrumb">
    <li><a href="{{ path('anuncios_anuncio_backend_user_index') }}">{{ 'gecko.backend.breadcrumb.user.index'|trans }}</a></li>
    <li>{{ 'gecko.backend.breadcrumb.new'|trans }}</li>
</ol>
{% endblock %}

{% block content %}
<div class="page-header">
    <h1><i class="icon-plus-sign"></i> {{ 'gecko.backend.user.create_header'|trans|raw }}</h1>
</div>

{{ form_errors(form) }}

<form action="{{ path('anuncios_anuncio_backend_user_create') }}" method="post" class="form-horizontal" enctype="multipart/form-data" novalidate>
    {% include 'AnunciosAnuncioBundle:Backend/User:_form.html.twig' %}
    {{ create() }}
</form>
{% endblock %}

src/Anuncios/AnuncioBundle/Resources/views/Backend/User/filterForm.html.twig
{% form_theme form 'GeckoBackendBundle::filterForms.html.twig' %}

<form method="get" action="{{ path('anuncios_anuncio_backend_user_index') }}" class="form-inline form-filter">
    {{ form_row(form.username) }}
    {{ form_row(form.isJurado) }}
    <button type="submit" class="btn btn-primary"><i class="icon-search"></i> Buscar</button>
</form>

src/Anuncios/AnuncioBundle/Resources/views/Backend/User/index.html.twig
{% extends 'GeckoBackendBundle::layout.html.twig' %}

{% import 'SyliusResourceBundle:Macros:buttons.html.twig' as buttons %}
{% from 'GeckoBackendBundle:Macros:misc.html.twig' import pagination %}
{% from 'AnunciosAnuncioBundle:Backend/User:macros.html.twig' import list  %}

{% block topbar %}
<ol class="breadcrumb">
    <li>{{ 'gecko.backend.breadcrumb.user.index'|trans }}</li>
</ol>
{% endblock %}

{% block content %}
<div class="page-header">
    <div class="actions-menu">
        {{ buttons.create(path('anuncios_anuncio_backend_user_create'), 'gecko.backend.create'|trans) }} 
    </div>
    <h1><i class="icon-user"></i> {{ 'gecko.backend.user.index_header'|trans|raw }}</h1>
</div>

{% render(controller('gecko.backend.controller.form:filterAction', {'type': 'anuncios_user_filter', 'template': 'AnunciosAnuncioBundle:Backend/User:filterForm.html.twig'})) %}

{{ list(users)  }}
{{ pagination(users) }}

{% endblock %}

src/Anuncios/AnuncioBundle/Resources/views/Backend/User/macros.html.twig
{% macro list(users) %}

{% import 'SyliusResourceBundle:Macros:buttons.html.twig' as buttons %}
{% import 'GeckoBackendBundle:Macros:alerts.html.twig' as alerts %}
{% import 'GeckoBackendBundle:Macros:misc.html.twig' as misc %}

{% if users|length > 0 %}
<table id="users" class="table">
    <thead>
        <tr>
            <th>{{ sylius_resource_sort('id', 'gecko.backend.id'|trans) }}</th>
            <th>Nombre y apellido</th>
            <th>{{ sylius_resource_sort('username', 'Nombre Usuario') }}</th>
            <th>{{ sylius_resource_sort('email', 'Email') }}</th>
            <th>{{ sylius_resource_sort('isjurado', 'Es Jurado?') }}</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr id="{{ user.id }}">
            <td>{{ user.id }}</td>
            <td>{{ user.fullname }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.email }}</td>
            {% if user.isjurado %}
            	<td>Si</td>
            {% else %}
            	<td>No</td>
            {% endif %}
            <td>
                <div class="pull-right">
                    {{ buttons.edit(path('anuncios_anuncio_backend_user_update', {'id': user.id})) }}
                    {{ buttons.delete(path('anuncios_anuncio_backend_user_delete', {'id': user.id})) }}
                </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
{{ alerts.info('gecko.backend.no_results'|trans) }}
{% endif %}

{% endmacro %}

src/Anuncios/AnuncioBundle/Resources/views/Backend/User/show.html.twig
{% extends 'SyliusWebBundle:Backend:layout.html.twig' %}

{% import 'SyliusResourceBundle:Macros:buttons.html.twig' as buttons %}

{% block topbar %}
<ol class="breadcrumb">
    <li>{{ 'sylius.breadcrumb.customers'|trans }}</li>
    <li><a href="{{ path('sylius_backend_user_index') }}">{{ 'sylius.breadcrumb.user.index'|trans }}</a></li>
    <li>{{ user.fullName  }}</li>
</ol>
{% endblock %}

{% block content %}
<div class="page-header">
    <div class="actions-menu">
        {{ buttons.manage(path('sylius_backend_user_index'), 'sylius.user.manage'|trans) }}
        {{ buttons.edit(path('sylius_backend_user_update', {'id': user.id})) }}
        {{ buttons.delete(path('sylius_backend_user_delete', {'id': user.id}), null, false, false) }}
    </div>
    <h1><i class="icon-info-sign"></i> {{ 'sylius.user.show_header'|trans|raw }}</h1>
</div>


<table class="table table-bordered">
    <thead>
        <tr>
            <th colspan="2">{{ 'sylius.user.general_info'|trans({'%username%': user.username}) }}</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><strong>{{ 'sylius.user.id'|trans }}</strong></td>
            <td>{{ user.id }}</td>
        </tr>
        {% if user.firstName %}
            <tr>
                <td><strong>{{ 'sylius.user.first_name'|trans }}</strong></td>
                <td>{{ user.firstName }}</td>
            </tr>
        {% endif %}
        {% if user.lastName %}
            <tr>
                <td><strong>{{ 'sylius.user.last_name'|trans }}</strong></td>
                <td>{{ user.lastName }}</td>
            </tr>
        {% endif %}
        <tr>
            <td><strong>{{ 'sylius.user.username'|trans }}</strong></td>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <td><strong>{{ 'sylius.user.email'|trans }}</strong></td>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <td><strong>{{ 'sylius.user.enabled'|trans }}</strong></td>
            <td>
                <span class="label label-{{ user.enabled ? 'success' : 'important'}}">
                    {{ user.enabled ? 'sylius.yes'|trans : 'sylius.no'|trans }}
                </span>
            </td>
        </tr>
        {% if user.lastLogin %}
        <tr>
            <td><strong>{{ 'sylius.user.last_login'|trans }}</strong></td>
            <td>{{ user.lastLogin|date }}</td>
        </tr>
        {% endif %}
    </tbody>
</table>

<div class="row">
    {% if user.shippingAddress %}
        <div class="col-md-6">
            {% include 'SyliusWebBundle:Backend/Address:_show.html.twig' with {'address': user.shippingAddress, 'title': 'sylius.user.shipping_address'|trans} %}
        </div>
    {% endif %}
    {% if user.billingAddress %}
        <div class="col-md-6">
            {% include 'SyliusWebBundle:Backend/Address:_show.html.twig' with {'address': user.billingAddress, 'title': 'sylius.user.billing_address'|trans} %}
        </div>
    {% endif %}
</div>
<div class="row">
    <div class="col-md-12">
        {% render(url('sylius_backend_order_by_user', app.request.query.all|merge({id: user.id}) )) %}
    </div>
</div>

{% endblock %}

src/Anuncios/AnuncioBundle/Resources/views/Backend/User/update.html.twig
{% extends 'GeckoBackendBundle::layout.html.twig' %}

{% from 'SyliusResourceBundle:Macros:actions.html.twig' import update %}

{% block topbar %}
<ol class="breadcrumb">
    <li><a href="{{ path('anuncios_anuncio_backend_user_index') }}">{{ 'gecko.backend.breadcrumb.user.index'|trans }}</a></li>
    <li>{{ 'gecko.backend.breadcrumb.edit'|trans }}</li>
</ol>
{% endblock %}

{% block content %}
<div class="page-header">
    <h1><i class="icon-pencil"></i> {{ 'gecko.backend.user.update_header'|trans|raw }}</h1>
</div>

{{ form_errors(form) }}

<form action="{{ path('anuncios_anuncio_backend_user_update', {'id': user.id}) }}" method="post" class="form-horizontal" enctype="multipart/form-data" novalidate>
    <input type="hidden" name="_method" value="PUT">
    {% include 'AnunciosAnuncioBundle:Backend/User:_form.html.twig' %}
    {{ update() }}
</form>
{% endblock %}